apps/main/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^orders/', include("orders.urls")),
    url(r'^statistics/', include("statistics.urls")),
    url(r'^', include("menu.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    ) + static(
        settings.STATIC_URL,
        document_root = settings.STATIC_ROOT
    )

apps/menu/urls.py
from django.conf.urls import include, url

from menu.views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view()),
]

apps/menu/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

class Category(models.Model):
    class Meta:
        verbose_name = u"Категория"
        verbose_name_plural = u"Категории"

    name = models.CharField(verbose_name=u"название", max_length=200, unique=True)

    def __unicode__(self):
        return self.name

class Dish(models.Model):
    class Meta:
        verbose_name = u"Блюдо"
        verbose_name_plural = u"Блюда"

    category = models.ForeignKey(Category, verbose_name=u"категория", on_delete=models.CASCADE)
    name = models.CharField(verbose_name=u"название", max_length=200, unique=True)
    cost = models.PositiveIntegerField(verbose_name=u"стоимость")
    image = models.ImageField(verbose_name=u"изображение", blank=True, null=True)

    def __unicode__(self):
        return self.name

apps/menu/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from menu.models import Dish, Category

class DishAdminModelForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ["name", "cost", "image", "category"]
        widgets = {
            "category": forms.TextInput()
        }

apps/menu/views.py
from django.views.generic.base import TemplateView

from menu.models import Category
from orders.models import Order, OrderItem

class HomePageView(TemplateView):
    template_name = u"menu/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated and hasattr(user, "client"):
            client_order, created = Order.objects.get_or_create(
                client = user.client,
                status = Order.STATUS_BASKET,
            )
        else:
            order_pk = self.request.session.get("order_pk", 0)
            client_order, created = Order.objects.get_or_create(
                pk = order_pk,
                status = Order.STATUS_BASKET
            )

        order_items = OrderItem.objects.filter(order = client_order)
        categories = Category.objects.filter(dish__isnull=False).distinct()
        basket_items = [{
            "dish_name": item.dish.name,
            "quantity": item.quantity,
            "price": item.quantity * item.dish.cost,
        } for item in order_items]
        in_total = reduce(lambda acc, x: acc + x["price"], basket_items, 0)

        context["basket_items"] = basket_items
        context["in_total"] = in_total
        context["categories"] = categories
        context["order_pk"] = client_order.pk
        return context

apps/menu/templates/menu/base.html
{% load staticfiles %}
<html>
  <head>
    <title>World Scills</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block includes %}
    <link href="{% static 'menu/css/libs/bootstrap_sandstone.css' %}" rel="stylesheet">
    <link href="{% static 'menu/css/style.css' %}" rel="stylesheet">

    <script src="{% static 'menu/js/libs/jquery.min.js' %}"></script>
    <script src="{% static 'menu/js/libs/bootstrap.min.js' %}"></script>
    {% endblock includes %}

  </head>
  <body>
    <div class="">
      <div class="row">

        <div class="col-md-8">
            <!-- Nav tabs -->
            {% block categories %}
            {% endblock categories %}

            <!-- Tab panes -->
            {% block tab-panes %}
            {% endblock tab-panes %}
        </div>

        <div class="col-md-4 calculator-container">
            {% block calculator %}
            {% endblock calculator %}
        </div>

      </div>
    </div>
  </body>
</html>

apps/menu/templates/menu/index.html
{% extends "menu/base.html" %}
{% load staticfiles %}

{% block includes %}
{{ block.super }}
<script type="text/javascript" src="{% static 'menu/js/menu.js' %}"></script>
{% endblock includes %}

{% block categories %}
<ul class="categories" role="tablist">
    {% for category in categories %}
        <li role="presentation"
            {% if forloop.counter == 1 %}
                class="active"
            {% endif %}>
            <a href="#tab-{{ forloop.counter }}"
                {% if forloop.counter == 1 %}
                    aria-expanded="true"
                {% endif %}
               aria-controls="tab-{{ forloop.counter }}"
               role="tab" data-toggle="tab">
                {{ category.name }}
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock categories %}


{% block tab-panes %}
<form name="menu" method="POST">{% csrf_token %}
    <div class="tab-content">
        {% for category in categories %}
            <div role="tabpanel"
                class="tab-pane {% if forloop.counter == 1 %} active {% endif %}"
                id="tab-{{ forloop.counter }}">

                <div class ="items">
                {% for dish in category.dish_set.all %}
                    <div class="item">
                        <div class="item-image">
                            <image src='{% if dish.image %}
                                            {{ dish.image.url }}
                                        {% endif %}'>
                            <div class='item-price'>{{ dish.cost }}</div>
                        </div>
                        <div class="item-description">{{ dish.name }}</div>
                    </div>
                {% endfor %}
                </div>

            </div>
        {% endfor %}
    </div>
</form>
{% endblock tab-panes %}

{% block calculator %}
<div class="calculator">
    <table class="table">
        <thead> <tr> <th></th> <th>Наименование</th> <th>Кол-во</th> <th>Цена</th>  <td></td></tr> </thead>
        <tbody>

        {% for basket_item in basket_items %}
            <tr class="basket-item" name="{{basket_item.dish_name}}">
                <th scope="row">{{forloop.counter}}</th>
                <td class="basket-item-name">{{basket_item.dish_name}}</td>
                <td class="basket-item-quantity"><input type="number" min='1' value="{{basket_item.quantity}}"></td>
                <td class="basket-item-price">{{basket_item.price}}</td>
                <td class="remove-dish-button">&#10006;</td>
            </tr>
        {% empty %}
            <tr class="basket-no-item"> <th></th> <th colspan="3">There are no items in the order.<th> </tr>
        {% endfor %}
            <tr>
                <th scope="row"></th>
                <th>Итого</th>
                <td></td>
                <th class="basket-in-total">{{ in_total }}</th>
            </tr>

        </tbody>
    </table>
    <div class="calc-buttons" >
        <form>
            <button class='calc-button calc-button-clean'>Очистить</button><button formaction="{% url 'cheque_url' order_pk %}" class='calc-button calc-button-checkout'>Оформить заказ</button>
        </form>
    </div>
</div>
{% endblock calculator %}